services:
  minio:
    # renovate: datasource=docker depName=minio/minio
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address ':9001'
    environment:
      - TZ=${TZ}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - /volume1/Minio:/data
      - /volume1/docker/minio/config:/root/.minio
      #- minio-data:/data
      #- minio-config:/root/.minio
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio-console.rule=Host(`minio.${LOCAL_DOMAIN}`)"
      - "traefik.http.routers.minio-console.entrypoints=web"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
      - "traefik.http.routers.minio-api.rule=Host(`s3.${LOCAL_DOMAIN}`)"
      - "traefik.http.routers.minio-api.entrypoints=web"
      - "traefik.http.services.minio-api.loadbalancer.server.port=9000"

#volumes:
#  minio-data:
#  minio-config:

networks:
  traefik_proxy:
    external: true
